### ISSUE TITLE
Doesn't work with macOS Sierra (10.12.x)

### ISSUE THREAD

**Issue by darcilicious** [francoisferland/casiousbmididriver#40]
The package installer appears to run fine but when I look in ~/Library/Audio/MIDI Drivers, it doesn't appear that anything was installed.

Is there any chance that you'll be working on an updated driver? I'm happy to test!

Thanks for reading.

**Comment by francoisferland** [comment]
The installer (casiousb.pkg) normally installs in /Library/Audio/MIDI Drivers. Can you confirm if it's there ? Also, does it show up in Audio/MIDI Configuration ?

**Comment by darcilicious** [comment]
Here's what I've got:
ls -lR MID*
MIDI Configurations:

MIDI Devices:
total 0
drwxr-xr-x  3 root  wheel  102 Jul 30  2016 Generic

MIDI Devices/Generic:
total 0
drwxr-xr-x  18 root  wheel  612 Jul 30  2016 Images

MIDI Devices/Generic/Images:
total 896
-rw-r--r--  1 root  wheel  63335 Jul 30  2016 AnalogKeyboard.pdf
-rw-r--r--  1 root  wheel  70831 Jul 30  2016 DrumMachine.pdf
-rw-r--r--  1 root  wheel  64417 Jul 30  2016 FullSizeSynth.pdf
-rw-r--r--  1 root  wheel  37820 Jul 30  2016 Groovebox.tiff
-rw-r--r--  1 root  wheel   7586 Jul 30  2016 IURack.tiff
-rw-r--r--  1 root  wheel  30475 Jul 30  2016 Interface1.pdf
-rw-r--r--  1 root  wheel   8744 Jul 30  2016 Interface2.tiff
-rw-r--r--  1 root  wheel  69940 Jul 30  2016 Keyboard.pdf
-rw-r--r--  1 root  wheel  17910 Jul 30  2016 MidSizeController.tiff
-rw-r--r--  1 root  wheel  15112 Jul 30  2016 MiniController.tiff
-rw-r--r--  1 root  wheel  40284 Jul 30  2016 Mixer.tiff
-rw-r--r--  1 root  wheel  34164 Jul 30  2016 Mixer2.tiff
-rw-r--r--  1 root  wheel  15586 Jul 30  2016 SilverLargeKeyboard.tiff
-rw-r--r--  1 root  wheel  19156 Jul 30  2016 ToneGenerator.tiff
-rw-r--r--  1 root  wheel  16106 Jul 30  2016 ToneGenerator2.tiff
-rw-r--r--  1 root  wheel  43608 Jul 30  2016 USBInterface.pdf

MIDI Drivers:
total 0
drwxr-xr-x  3 darci  staff  102 Aug 23  2011 CasioUSBMIDIDriver.plugin

MIDI Drivers/CasioUSBMIDIDriver.plugin:
total 0
drwxr-xr-x  5 darci  staff  170 Jun 10 17:58 Contents

MIDI Drivers/CasioUSBMIDIDriver.plugin/Contents:
total 8
-rw-r--r--  1 darci  staff  1360 Aug 23  2011 Info.plist
drwxr-xr-x  3 darci  staff   102 Jun 10 17:58 MacOS
drwxr-xr-x  3 darci  staff   102 Jun 10 17:58 Resources

MIDI Drivers/CasioUSBMIDIDriver.plugin/Contents/MacOS:
total 184
-rwxr-xr-x  1 darci  staff  92988 Aug 23  2011 CasioUSBMIDIDriver

MIDI Drivers/CasioUSBMIDIDriver.plugin/Contents/Resources:
total 8
-rw-r--r--  1 darci  staff  1220 Aug 23  2011 Info-CasioUSBMIDIDriver.plist

MIDI Patch Names:


So, nothing under Configurations or Patch Names.

**Comment by darcilicious** [comment]
SO embarrassing. Operator error, it's working just fine now.
