### ISSUE TITLE
macOS Mojave?

### ISSUE THREAD

**Issue by SeptemberB** [francoisferland/casiousbmididriver#41]
Just want to know if this works for the latest update (10.14.2).
thanks.

**Comment by francoisferland** [comment]
I haven't had the chance to test it yet, but I do not believe there have been major changes since the last version.

**Comment by spritipe** [comment]
I installed the drivers but it doesn't seem to be working, I was wondering if anyone could got it to work on Mojave?
Thank you!

**Comment by spritipe** [comment]
The error does not happen if I remove it, it only happens when I have your plug-in installed and my Casio LK-93TV connected via USB.

Thank you for trying to help

**Comment by spritipe** [comment]
Actually reinstalling it worked, all good! 👍

**Comment by antonio-krm** [comment]
Heyy i am currently on MacOs Mojave and using a Casio ctk-2000, and every time I open the Audio MIDI Setup I get a weird error (wether the keyboard is connected or not). I tried reinstalling and still didn't work for some reason: 
![Screen Shot 2020-05-27 at 1 07 55 PM](https://user-images.githubusercontent.com/63870685/83006798-68246c00-a01b-11ea-9ce6-167659625359.png)
