### ISSUE TITLE
MacOs Mojave Error

### ISSUE THREAD

**Issue by ghost** [francoisferland/casiousbmididriver#42]
Heyy i am currently on MacOs Mojave and using a Casio ctk-2000, and every time I open the Audio MIDI Setup I get a weird error (wether the keyboard is connected or not). I tried reinstalling and still didn't work for some reason: 
![83006798-68246c00-a01b-11ea-9ce6-167659625359](https://user-images.githubusercontent.com/63870685/83007613-99ea0280-a01c-11ea-8796-cefb6ebacb37.png)

**Comment by francoisferland** [comment]
Hi, unfortunately I no longer have regular access to a Casio keyboard and cannot fully test the driver in recent macOS versions. If I get a keyboard again I will test it. In the mean time, could you look into the macOS console.app to see if any Casio-related error messages appear ?

**Comment by antonio-krm** [comment]
Heyy thank you for replying,
I checked my console and i do seem to get some casio related activity:


The weird thing is though that when i have my keyboard connected, i either
do or do not get the error message pop up:

“The MIDI Server can’t be opened.
Audio MIDI  Setup couldn’t open the MIDI Server so you can’t view or edit
your MIDI configurations. If you recently installed a new MIDI driver, try
uninstalling it and then open Audio Midi Setup again. If Audio MIDI Setup
works correctly after that, contact the driver’s manufacturer for further
support.”


But, in both cases (when the popup appears or when it doesnt) all i dont
see the casio driver, just the IAC Driver in the cases when i do not get
the popup.

Again, thank you for you time :)
