### ISSUE TITLE
Installation fails on Catalina

### ISSUE THREAD

**Issue by ipince** [francoisferland/casiousbmididriver#43]
Hi!  Thanks for putting this driver together.

I tried installing it on Mac OS Catalina (Version 10.15.6), but the installer just seems to be a no-op. From #41 , it seems that the installer should drop some files into `/Library/Audio/MIDI Drivers/`, but after running the installer, my `/Library/Audio/MIDI Drivers/` is still empty.

Any ideas on how to troubleshoot?  Thanks!

Not that it matters, but I'm trying to get this to work on a Casio Privia PX-135, and it seems like it'll be a challenge...

**Comment by francoisferland** [comment]
Hi, I'm happy if it can be helpful!

Unfortunately, I no longer have access to a Casio keyboard to test it myself, but you could try copying the plugin file directly in that location. I attached the driver to this message.
[CasioUSBMIDIDriver.plugin.zip](https://github.com/francoisferland/casiousbmididriver/files/5029314/CasioUSBMIDIDriver.plugin.zip)

**Comment by ipince** [comment]
Thanks for the zipfile!

I ended up getting a hold of a Windows machine. If things fail there (or even if they work but I'm curious/have time), I'll come back to trying to make it work on my Mac.

**Comment by erikvdplas** [comment]
Any chance you still got this working on Mac with this (or another) plugin?

**Comment by francoisferland** [comment]
Hi, I can confirm the plugin works on macOS Monterey 12.6 on a MacBook Air M2. You just need to manually authorize the plugin in your security settings (might take a few times and require restarting GarageBand or any other software before it takes).
