### ISSUE TITLE
Not working on my Macbook Pro 2013 and macOS BigSur 11.6.2

### ISSUE THREAD

**Issue by MartinLA0416** [francoisferland/casiousbmididriver#45]
Hi, I have a Casio CTX-800 keyboard and I connect from the USB port of the keyboard to my computer. Nothing really happens. The audio midi setup does not show any new MIDI device.

**Comment by francoisferland** [comment]
Hi, the CTX-800 is a more recent keyboard that is USB MIDI compliant and should work « out of the box » without a specific driver. Unfortunately this driver will not be helpful as it is meant for older keyboards that were not fully compliant.

**Comment by MartinLA0416** [comment]
> Hi, the CTX-800 is a more recent keyboard that is USB MIDI compliant and should work « out of the box » without a specific driver. Unfortunately this driver will not be helpful as it is meant for older keyboards that were not fully compliant.

Thank you very much for your reply, I will try again without the driver. 
So as you said, it is possible to connect the CTX-800 with my Macbook Pro 2013 with the USB type A cable, without the driver installed into the MIDI Driver folder?

**Comment by MartinLA0416** [comment]
> Hi, the CTX-800 is a more recent keyboard that is USB MIDI compliant and should work « out of the box » without a specific driver. Unfortunately this driver will not be helpful as it is meant for older keyboards that were not fully compliant.
